// test-pdf.mjs - 测试 PDF 生成功能

import { mdToPdf } from './src/utils.mjs';

const testMd = `# 智能协作平台技术方案

## 项目概述

这是一个高度智能化的协作平台，支持多 Agent 串行与并行执行，可视化工作流编排，让团队协作更高效。

### 核心价值

- 高性能: RPC 模式，~200ms 启动延迟
- 可扩展: 25+ Agent 动态加载
- 记忆系统: 四层 Memory 分层架构
- 可视化: 实时工作流监控面板

## 技术架构

### 三层路由设计

\`\`\`
Discord Messages
       |
       v
+-----------------+
|     Router      |
+--------+--------+
         |
         v
+--------+--------+
| !command  自由文本 |
| CommandRouter Multi-Agent |
+-----------------+
\`\`\`

### Agent 列表

| Agent | 职责 | Memory Scope |
|-------|------|--------------|
| orchestrator | 战略协调 | agent-internal |
| sales | 销售线索 | sales |
| dev | 代码生成 | coding |
| distill | 内容蒸馏 | content |

## 代码示例

\`\`\`javascript
const pi = new RpcClient({
  cliPath: '/path/to/pi/cli.js',
  cwd: ROOT,
  provider: 'minimax-cn',
  model: 'MiniMax-M3',
});

await pi.start();
\`\`\`

## 引用块测试

> 这是一个引用块，用于展示重要信息。
> **核心价值**: 让 AI Agent 协作更简单、更高效。

## 功能清单

1. 多 Agent 自动化协作
2. 长期记忆与上下文管理
3. 定时任务与工作流自动化
4. 实时监控与告警

## 总结

通过本方案的实施，可以实现团队协作效率的显著提升。

---

Generated by pi-discord-agents
`;

async function main() {
  console.log('Testing PDF generation...\n');

  const result = await mdToPdf(testMd, '智能协作平台技术方案', '/tmp/test-beautiful-v2.pdf', {
    author: 'pi-discord-agents Team',
    accentColor: '#1a365d',
  });

  if (result) {
    console.log('PDF generated successfully!');
    console.log('File: /tmp/test-beautiful-v2.pdf');
  } else {
    console.log('PDF generation failed');
  }
}

main().catch(console.error);
